#!/bin/bash
echo "-rw-r--r-- 1 root root 102 Feb  8 03:37 0-current_working_directory                                                                               

-rw-r--r-- 1 root root 167 Feb  8 04:11 1-listit                                                                                                  

-rw-r--r-- 1 root root  32 Feb  8 04:58 2-bring_me_home                                                                                           

-rw-r--r-- 1 root root 102 Feb  8 05:08 3-listfiles                                                                                               

-rw-r--r-- 1 root root  16 Feb  8 02:54 README.md"
